// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOZ9toKZ55DYRwN--lUPnBYvXGVgaGOBs',
    appId: '1:442332212555:web:8166116b1c0e05ebdb4cce',
    messagingSenderId: '442332212555',
    projectId: 'order-management-app-ab92a',
    authDomain: 'order-management-app-ab92a.firebaseapp.com',
    storageBucket: 'order-management-app-ab92a.firebasestorage.app',
    measurementId: 'G-9P81JD0WSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAifIh9M2hW164Rl45-gE5etsE5aJ7B1tM',
    appId: '1:442332212555:android:912a82cf3103858adb4cce',
    messagingSenderId: '442332212555',
    projectId: 'order-management-app-ab92a',
    storageBucket: 'order-management-app-ab92a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf55WTx4f81fd9kqjawHSAqOTi3RPE4hA',
    appId: '1:442332212555:ios:1510351dc79ea9afdb4cce',
    messagingSenderId: '442332212555',
    projectId: 'order-management-app-ab92a',
    storageBucket: 'order-management-app-ab92a.firebasestorage.app',
    iosBundleId: 'com.example.ordermanagement.orderManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf55WTx4f81fd9kqjawHSAqOTi3RPE4hA',
    appId: '1:442332212555:ios:1510351dc79ea9afdb4cce',
    messagingSenderId: '442332212555',
    projectId: 'order-management-app-ab92a',
    storageBucket: 'order-management-app-ab92a.firebasestorage.app',
    iosBundleId: 'com.example.ordermanagement.orderManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOZ9toKZ55DYRwN--lUPnBYvXGVgaGOBs',
    appId: '1:442332212555:web:c5dd76f9939570c9db4cce',
    messagingSenderId: '442332212555',
    projectId: 'order-management-app-ab92a',
    authDomain: 'order-management-app-ab92a.firebaseapp.com',
    storageBucket: 'order-management-app-ab92a.firebasestorage.app',
    measurementId: 'G-JQ6LRMQL25',
  );
}
